final List<String> cities = [
  "Karachi",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Gujranwala",
  "Peshawar",
  "Multan",
  "Islamabad",
  "Quetta",
  "Naples",
  "Tando Jam",
  "Tokyo",
  "Delhi",
  "Shanghai",
  "São Paulo",
  "Mumbai",
  "Beijing",
  "Mexico City",
  "Osaka",
  "Cairo",
  "New York City",
  "Dhaka",
  "Buenos Aires",
  "Istanbul",
  "Chongqing",
  "Kolkata",
  "Lagos",
  "Kinshasa",
  "Manila",
  "Rio de Janeiro",
  "Tianjin",
  "Guangzhou",
  "Los Angeles",
  "Moscow",
  "Shenzhen",
  "Bangalore",
  "Paris",
  "Bogotá",
  "Jakarta",
  "Chennai",
  "Lima",
  "Bangkok",
  "Hyderabad",
  "Seoul",
  "Nagoya",
  "Chicago",
  "London",
  "Tehran",
  "Shijiazhuang",
  "Wuhan",
  "Ho Chi Minh City",
  "Luanda",
  "Hong Kong",
  "Dongguan",
  "Hangzhou",
  "Foshan",
  "New Taipei City",
  "Kuala Lumpur",
  "Santiago",
  "Saint Petersburg",
  "Ahmedabad",
  "Surat",
  "Suwon",
  "Madrid",
  "Pune",
  "Houston",
  "Dallas",
  "Toronto",
  "Miami",
  "Philadelphia",
  "Atlanta",
  "Washington, D.C.",
  "Boston",
  "San Francisco",
  "Detroit",
  "Seattle",
  "Phoenix",
  "Minneapolis",
  "San Diego",
  "Denver",
  "Tampa",
  "Orlando",
  "Austin",
  "Las Vegas",
  "Portland",
  "Charlotte",
  "New Orleans",
  "Indianapolis",
  "Nashville",
  "Columbus",
  "Sacramento",
  "Kansas City",
  "Salt Lake City",
  "San Antonio",
  "Raleigh",
  "Cleveland",
  "Cincinnati",
  "Milwaukee",
  "Saint Louis",
  "San Jose",
  "Jacksonville",
  "Fort Worth",
  "Fortaleza",
  "Manaus",
  "Salvador",
  "Curitiba",
  "Recife",
  "Porto Alegre",
  "Campinas",
  "Belém",
  "Goiânia",
  "Guarulhos",
  "Brasília",
  "Santo Domingo",
  "Montevideo",
  "La Paz",
  "Santa Cruz de la Sierra",
  "Quito",
  "Córdoba",
  "Rosario",
  "Tucumán",
  "La Plata",
  "Mar del Plata",
  "San Miguel de Tucumán",
  "Santa Fe",
  "Salta",
  "Corrientes",
  "Bahía Blanca",
  "Resistencia",
  "Posadas",
  "San Salvador de Jujuy",
  "Neuquén",
  "Formosa",
  "San Juan",
  "Comodoro Rivadavia",
  "Santiago del Estero",
  "Río Gallegos",
  "Concordia",
  "San Luis",
  "La Rioja",
  "Catamarca",
  "Viedma",
  "Rawson",
  "Ushuaia",
  "Chelyabinsk",
  "Kazan",
  "Samara",
  "Ufa",
  "Perm",
  "Omsk",
  "Rostov-on-Don",
  "Volgograd",
  "Krasnoyarsk",
  "Barnaul",
  "Vladivostok",
  "Irkutsk",
  "Khabarovsk",
  "Yakutsk",
  "Vladikavkaz",
  "Novosibirsk",
  "Yekaterinburg",
  "Krasnodar",
  "Nizhny Novgorod",
  "Tomsk",
  "Kemerovo",
  "Tyumen",
  "Orenburg",
  "Novokuznetsk",
  "Cheboksary",
  "Penza",
  "Bryansk",
  "Smolensk",
  "Kaluga",
  "Tula",
  "Lipetsk",
  "Yaroslavl",
  "Tver",
  "Ryazan",
  "Ivanovo",
  "Belgorod",
  "Kursk",
  "Voronezh",
  "Tambov",
  "Astrakhan",
  "Taganrog",
  "Novorossiysk",
  "Sevastopol",
  "Simferopol",
  "Kiev",
  "Kharkiv",
  "Dnipro",
  "Odessa",
  "Donetsk",
  "Zaporizhzhia",
  "Lviv",
  "Kryvyi Rih",
  "Mykolaiv",
  "Mariupol",
  "Luhansk",
  "Vinnytsia",
  "Makiivka",
  "Enerhodar",
  "Kirovohrad",
  "Kherson",
  "Khmelnytskyi",
  "Cherkasy",
  "Chernihiv",
  "Chernivtsi",
  "Kremenchuk",
  "Sumy",
  "Rivne",
  "Ternopil",
  "Ivano-Frankivsk",
  "Lutsk",
  "Uzhhorod",
  "Bila Tserkva",
  "Yalta",
  "Kramatorsk",
  "Melitopol",
  "Nikopol",
  "Slavyansk",
  "Uman",
  "Lysychansk",
  "Mukacheve",
  "Yenakiieve",
  "Lisichansk",
  "Krasnyi Luch",
  "Brovary",
  "Bakhchisaray",
  "Brovary"
];
